### ISSUE TITLE
XMLLint doesn't open on time

### ISSUE THREAD

**Issue by pchris7489** [mluis7/xml2xpath#10] opened 2024-06-06 13:45 UTC
Hello,

There is one bug in the script, in function `get_xml_tree` on line `"${lint_cmd[@]}" "$xml_file" 1>&3 2>/dev/null <&4 &` (CTRL+F)

It is neccessary to put a code in this style (note : this code doesn't detect the PID of the correct xmllint)

`until pgrep xmllint; do sleep 2; done 1>&2>/dev/null`

Sometimes, on some computers (virtual machines, slow computers, fast computers with antiviruses, etc), the code will start processing the output on xmllint before even xmllint open

Thank you for handling this observation

**Comment by mluis7** [comment] 2024-06-17 19:21
@pchris7489 
`xmllint` reads and writes from FIFO files so this issue looks like a duplicate of issue #11 (or the opposite lol).
`read -r -u 3 -t 3` reads from fifo fd 3 which timeouts because `xmllint` has not read a command from fd 4 yet and has not written the output to fd 3.
The right fix seems to extend the `read` timeout.

**Comment by mluis7** [comment] 2024-06-18 20:52
Closed as a duplicate of #11

**Closed** 2024-06-18 21:11 UTC
Labels: bug
